ARG RUST_VERSION=1.89
FROM docker.io/rust:${RUST_VERSION}-trixie AS dependency
WORKDIR /opt/app

RUN mkdir -p setup/src && echo "fn main() {}" >> setup/src/main.rs
RUN mkdir -p core/src && echo "fn main() {}" >> core/src/main.rs

COPY Cargo.toml .
COPY .env.example .env.example
COPY Cargo.lock .
COPY setup/Cargo.toml setup/Cargo.toml
COPY core/Cargo.toml core/Cargo.toml

RUN cd setup && cargo fetch

FROM dependency AS build

RUN rustup target add x86_64-unknown-linux-musl
RUN apt-get update && apt-get install -y musl-tools

COPY setup/src setup/src
RUN --mount=type=cache,target=/opt/target/ \
    --mount=type=bind,source=Cargo.toml,target=Cargo.toml  \
    --mount=type=bind,source=Cargo.lock,target=Cargo.lock  \
    --mount=type=cache,target=/usr/local/cargo/registry/ \
	cd setup && \
    cargo build --target=x86_64-unknown-linux-musl --release --bin setup && \
    cp ../target/x86_64-unknown-linux-musl/release/setup /bin/setup

FROM debian:bullseye-slim AS final

# See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
RUN apt-get update && apt-get install --no-install-recommends -y ca-certificates wget && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN wget https://garagehq.deuxfleurs.fr/_releases/v2.1.0/x86_64-unknown-linux-musl/garage
RUN chmod +x garage && mv garage /bin/garage

RUN mkdir -p /opt/app && touch /opt/app/.env

# Copy the executable from the "build" stage.
COPY --from=build /bin/setup /bin/

CMD ["/bin/setup", "setup-s3", "env"]

